<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ComparisonTool\**" />
    <EmbeddedResource Remove="ComparisonTool\**" />
    <None Remove="ComparisonTool\**" />
    <Page Remove="ComparisonTool\**" />
  </ItemGroup>

</Project>
